import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import iclogo from '../public/ic_logo.svg'
import Image from 'next/image'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.mask}>
          <div className={styles.headerpart}>
            <Image src={iclogo} />
            <div className={styles.headertext}>
              Chase your Luck by Pre-Registering with Us!
            </div>
          </div>
          <form>
            <div className="row">
              <div className="col-sm-3">
                <small >First Name *</small>
                <input type="text" name='firstname' placeholder='Enter first name' className={styles.inputfield}/>
              </div>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default Home
