import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import iclogo from '../public/ic_logo.svg'
import Image from 'next/image'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.mask}>
          <div className={styles.headerpart}>
            <Image src={iclogo} />
            <div className={styles.headertext}>
              Chase your Luck by Pre-Registering with Us!
            </div>
          </div>
          <form className={styles.displayform}>
            <div className="row">
              <div className="col-sm-6">
                <small className='text-light'>First Name *</small>
                <input type="text" name='firstname' placeholder='Enter first name' className={styles.inputfield} />
              </div>
              <div className="col-sm-6">
                <small className='text-light'>Middle Name *</small>
                <input type="text" name='middlename' placeholder='Enter first name' className={styles.inputfield} />
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <small className='text-light'>Last Name *</small>
                <input type="text" name='lastname' placeholder='Enter first name' className={styles.inputfield} />
              </div>
              <div className="col-sm-6 radio">
                <small className='text-light form-label'>Gender</small><br />
                <input type='checkbox' className='form-check-input' />
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <small className='text-light'>Last Name *</small>
                <input type="date" name='date' placeholder='Enter first name' className={styles.inputfield} />
              </div>
              <div className="col-sm-6 radio">
                <small className='text-light'>Email ID *</small><br />
                <input type='email' className={styles.inputfield} />
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <small className='text-light'>Phone</small>
                <input type="telephone" name='date' placeholder='Enter first name' className={styles.inputfield} />
              </div>
              <div className="col-sm-6 radio">
                <small className='text-light'>Address Line 1</small><br />
                <input type='email' className={styles.inputfield} />
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <small className='text-light'>Address Line 2</small>
                <input type="text" name='date' placeholder='Enter first name' className={styles.inputfield} />
              </div>
              <div className="col-sm-6 radio">
                <small className='text-light'>Country</small><br />
                <select className={styles.inputfield}>
                  <option></option>
                </select>
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <small className='text-light'>City</small>
                <select className={styles.inputfield}>
                  <option></option>
                </select>
              </div>
              <div className="col-sm-6 radio">
                <small className='text-light'>Zip Code</small><br />
                <select className={styles.inputfield}>
                  <option></option>
                </select>
              </div>
            </div>
            <div className="row">
              <div className={styles.footer}>
                <div className={styles.formfooter}>
                  <input type="checkbox" />
                  I agree with the Terms & Conditions
                </div>
                <div className={styles.formfooter}>
                  <input type="checkbox" />
                  Please confirm that you are alteast 18 years old
                </div>
              </div>
            </div>
            <div className='row'>
              <button type='submit' className={styles.submitbutton}>REGISTER</button>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default Home
