import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import iclogo from '../public/ic_logo.svg'
import Image from 'next/image'
import { useForm, SubmitHandler } from 'react-hook-form'

type Inputs = {
  firstname: string
  middlename: string
  lastname: string
  gender: string
  dob: string
  emailid: string
  countrycode: string
  phoneno: number
  address1: string
  address2: string
  country: string
  city: string
  zipcode: number
  termsandconditions: boolean
  agerestriction: boolean
}

const Home: NextPage = () => {
  const { register, handleSubmit, formState: { errors } } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = data => {
    console.log(data)
  }

  return (
    <div>
      <Head>
        <title>PlayLootoGlobal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="ic_logo.svg" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.mask}>
          <div className={styles.headerpart}>
            <Image src={iclogo} width="150" height="180" />
            <div className={styles.headertext}>
              Chase your Luck by Pre-Registering with Us!
            </div>
          </div>
          <form className={styles.displayform} onSubmit={handleSubmit(onSubmit)}>
            <div className="row">
              <div className="col-sm-6">
                <label className={styles.formlabel}>First Name *</label>
                <input
                  type="text"
                  {...register("firstname", {
                    required: "Firstname required",
                    pattern: /^[a-zA-Z ]+$/
                  })}
                  placeholder='Enter first name'
                  className={styles.inputfield}
                />
                <span className={styles.error}>{errors.firstname?.message}</span>
                {errors.firstname?.type === "pattern" && <span className={styles.error}>Alphabetical characters only</span>}
              </div>
              <div className="col-sm-6">
                <label className={styles.formlabel}>Middle Name *</label>
                <input
                  type="text"
                  {...register("middlename", {
                    required: "Middlename required",
                    pattern: /^[a-zA-Z ]+$/
                  })}
                  placeholder='Enter middle name'
                  className={styles.inputfield}
                />
                <span className={styles.error}>{errors.middlename?.message}</span>
                {errors.middlename?.type === "pattern" && <span className={styles.error}>Alphabetical characters or whitespace only</span>}
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <label className={styles.formlabel}>Last Name *</label>
                <input
                  type="text"
                  {...register("lastname", {
                    required: "Lastname required",
                    pattern: /^[a-zA-Z ]+$/
                  })}
                  placeholder='Enter last name'
                  className={styles.inputfield}
                />
                <span className={styles.error}>{errors.lastname?.message}</span>
                {errors.lastname?.type === "pattern" && <span className={styles.error}>Alphabetical characters only</span>}
              </div>
              <div className={styles.radio + " col-sm-6"}>
                <label className={styles.formlabel}>Gender</label>
                <div className={styles.formgender}>
                  <input type='radio' title='Male' checked {...register("gender")} value="Male" /> Male
                  <input type='radio' title='Female' {...register("gender")} value="Female" /> Female
                  <input type='radio' title='Others' {...register("gender")} value="Others" /> Others
                </div>
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <label className={styles.formlabel}>DOB</label>
                <input
                  type="date"
                  {...register("dob")}
                  className={styles.inputfield}
                  title='Enter DOB' />
              </div>
              <div className="col-sm-6 radio">
                <label className={styles.formlabel}>Email ID *</label>
                <input
                  type='email'
                  {...register("emailid", {
                    required: "Email ID required",
                    pattern: /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/
                  })}
                  className={styles.inputfield}
                  placeholder='Enter email id'
                />
                <span className={styles.error}>{errors.emailid?.message}</span>
                {errors.emailid?.type === "pattern" && <span className={styles.error}>Email id must constain one @ and .</span>}
              </div>
            </div>
            <div className='row'>
              <div className=" col-sm-6">
                <label className={styles.formlabel}>Phone</label>
                <div className={styles.phone}>
                  <select
                    title='Country code'
                    className={styles.countrycode}
                    {...register("countrycode", {
                      maxLength: 10
                    })}
                  >
                    <option className={styles.selectoption}>1</option>
                  </select>
                  <input type="telephone" {...register("phoneno")} placeholder='Enter phone number' className={styles.inputphone} />
                </div>
              </div>
              <div className="col-sm-6">
                <label className={styles.formlabel}>Address Line 1</label>
                <input
                  type='email'
                  {...register("address1")}
                  className={styles.inputfield}
                  placeholder="Enter street address"
                />
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <label className={styles.formlabel}>Address Line 2</label>
                <input
                  type="text"
                  {...register("address2")}
                  placeholder="Enter apartment address"
                  className={styles.inputfield}
                />
              </div>
              <div className="col-sm-6 radio">
                <label className={styles.formlabel}>Country</label>
                <select
                  className={styles.inputfield}
                  title='Select country'
                  {...register("country")}
                >
                  <option disabled> - Select - </option>
                </select>
              </div>
            </div>
            <div className='row'>
              <div className="col-sm-6">
                <label className={styles.formlabel}>City</label>
                <select
                  className={styles.inputfield}
                  title='Select city'
                  {...register("city")}>
                  <option disabled> - Select - </option>
                </select>
              </div>
              <div className="col-sm-6 radio">
                <label className={styles.formlabel}>Zip Code</label>
                <select
                  className={styles.inputfield}
                  title="Select zip code"
                  {...register("zipcode")}
                >
                  <option disabled> - Select - </option>
                </select>
              </div>
            </div>
            <div className={styles.footer}>
              <div className={styles.formfooter}>
                <input
                  type="checkbox"
                  title='I agree with the Terms & Conditions'
                  {...register("termsandconditions", {
                    required: true
                  })}
                />
                <span className={errors.termsandconditions ? styles.footererror : styles.footertext}>I agree with the <a href='#' className={styles.aterms}>Terms & Conditions</a></span>
              </div>
              <div className={styles.formfooter}>
                <input
                  type="checkbox"
                  title='Please confirm that you are atleast 18 years old'
                  {...register("agerestriction", {
                    required: true
                  })}
                />
                <span className={errors.agerestriction ? styles.footererror : styles.footertext}>Please confirm that you are alteast 18 years old</span>
              </div>
            </div>
            <div className={styles.submitbuttondiv+' col text-center'}>
              <button type='submit' className={styles.submitbutton}>REGISTER</button>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default Home


